version: "3.8"
services:
  backend:
    build: backend/
    ports:
      - "5000:80"
    environment:
      - "PORT=80"
      - "FRONTEND_PORT=5000"
    volumes:
      - ./backend:/worker
    depends_on:
      - "db"
  frontend:
    stdin_open: true
    build: frontend/
    environment:
      - "PORT=80"
    volumes:
      - ./frontend:/worker
  db:
    image: "mongo:3.6.20"
